### ISSUE TITLE
Fix the Celestia network test suite

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/orchestrator-relayer#104]
Currently, when running the test node, we get the following error:
```
failed to listen on 127.0.0.1:26657: listen tcp 127.0.0.1:26657: bind: address already in use
```
This is also discussed in here: https://github.com/celestiaorg/celestia-app/pull/1342

To be able to reproduce the issue, the following repo contains the test: https://github.com/SweeXordious/orchestrator-relayer/tree/not_working_test_poc

```sh
$ go clean -testcache
$ make test
```

In the first run, only the relayer test will fail. However, when running the above commands again (make sure to clean the test cache before each run), also the orchestrator will fail with the above error.

**Comment by SweeXordious** [comment]
Could be also related to the following logs when starting the tests:
```
E[2023-02-08|18:18:06.283] Error serving server                         err="accept tcp 127.0.0.1:26657: use of closed network connection"
E[2023-02-08|18:18:06.283] Stopped accept routine, as transport is closed module=p2p numPeers=0
```

**Comment by SweeXordious** [comment]
The running go routines after shutting down the node:
```
goroutine 68 [running]:
github.com/celestiaorg/orchestrator-relayer/orchestrator_test.(*OrchestratorTestSuite).TearDownSuite(0xc0000cbe00)
	/something/Tmp/orchestrator-relayer/orchestrator/suite_test.go:26 +0xf7
github.com/stretchr/testify/suite.Run.func2()
	/something/go/pkg/mod/github.com/stretchr/testify@v1.8.1/suite/suite.go:183 +0xc8
github.com/stretchr/testify/suite.Run(0xc000f15520, {0x3aaafa8, 0xc0000cbe00})
	/something/go/pkg/mod/github.com/stretchr/testify@v1.8.1/suite/suite.go:194 +0x914
github.com/celestiaorg/orchestrator-relayer/orchestrator_test.TestOrchestrator(0xc000f15520)
	/something/Tmp/orchestrator-relayer/orchestrator/suite_test.go:31 +0x45
testing.tRunner(0xc000f15520, 0x387f3d0)
	/usr/lib/go/src/testing/testing.go:1446 +0x1ca
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x69e

goroutine 1 [chan receive]:E[2023-02-08|18:18:06.283] Error serving server                         err="accept tcp 127.0.0.1:26657: use of closed network connection"
E[2023-02-08|18:18:06.283] Stopped accept routine, as transport is closed module=p2p numPeers=0
testing.(*T).Run(0xc000f15520, {0x3185912, 0x10}, 0x387f3d0)
	/usr/lib/go/src/testing/testing.go:1494 +0x6c5
testing.runTests.func1(0xc000f15040)
	/usr/lib/go/src/testing/testing.go:1846 +0xcb
testing.tRunner(0xc000f15040, 0xc0010359e0)
	/usr/lib/go/src/testing/testing.go:1446 +0x1ca
testing.runTests(0xc000139830, {0x49a18d0, 0x1, 0x1}, {0x0, 0x0, 0x0})
	/usr/lib/go/src/testing/testing.go:1844 +0x44f
testing.(*M).Run(0xc00125b4a0)
	/usr/lib/go/src/testing/testing.go:1726 +0xb28
main.main()
	_testmain.go:47 +0xbc

goroutine 24 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00055e080)
	/something/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x12c
created by go.opencensus.io/stats/view.init.0
	/something/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0xb7

goroutine 14 [IO wait]:
internal/poll.runtime_pollWait(0x0?, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:305 +0x45
internal/poll.(*pollDesc).wait(0xc000067c18, 0x72, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x88
internal/poll.(*pollDesc).waitRead(0xc000067c18, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89 +0x37
internal/poll.(*FD).ReadMsg(0xc000067c00, {0xc000dfe670, 0x10, 0x10}, {0xc000db9320, 0x1000, 0x1000}, 0x40000000)
	/usr/lib/go/src/internal/poll/fd_unix.go:304 +0x545
net.(*netFD).readMsg(0xc000067c00, {0xc000dfe670, 0x10, 0x10}, {0xc000db9320, 0x1000, 0x1000}, 0x40000000)
	/usr/lib/go/src/net/fd_posix.go:78 +0xf1
net.(*UnixConn).readMsg(0xc000014800, {0xc000dfe670, 0x10, 0x10}, {0xc000db9320, 0x1000, 0x1000})
	/usr/lib/go/src/net/unixsock_posix.go:115 +0xfc
net.(*UnixConn).ReadMsgUnix(0xc000014800, {0xc000dfe670, 0x10, 0x10}, {0xc000db9320, 0x1000, 0x1000})
	/usr/lib/go/src/net/unixsock.go:143 +0x106
github.com/godbus/dbus.(*oobReader).Read(0xc000db9300, {0xc000dfe670, 0x10, 0x10})
	/something/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/transport_unix.go:21 +0xdd
io.ReadAtLeast({0x3aa2920, 0xc000db9300}, {0xc000dfe670, 0x10, 0x10}, 0x10)
	/usr/lib/go/src/io/io.go:332 +0x15c
io.ReadFull({0x3aa2920, 0xc000db9300}, {0xc000dfe670, 0x10, 0x10})
	/usr/lib/go/src/io/io.go:351 +0xa5
github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc00002a978)
	/something/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/transport_unix.go:91 +0x245
github.com/godbus/dbus.(*Conn).inWorker(0xc000d922d0)
	/something/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/conn.go:294 +0x5d
created by github.com/godbus/dbus.(*Conn).Auth
	/something/go/pkg/mod/github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2/auth.go:118 +0x12b5

goroutine 16 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc000f71f80, 0xc000f71ec0)
	/something/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:36 +0x52
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/something/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:29 +0x27e

goroutine 66 [chan receive]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc000f71f80, 0xc000f71f20)
	/something/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:81 +0x5b
created by github.com/rjeczalik/notify.newNonrecursiveTree
	/something/go/pkg/mod/github.com/rjeczalik/notify@v0.9.1/tree_nonrecursive.go:30 +0x316

goroutine 67 [select]:
github.com/desertbit/timer.timerRoutine()
	/something/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:119 +0x11b
created by github.com/desertbit/timer.init.0
	/something/go/pkg/mod/github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f/timers.go:15 +0x25

goroutine 71 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc001222000)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x99a
created by github.com/syndtr/goleveldb/leveldb.newSession
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x469

goroutine 72 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc001066700)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:91 +0xf8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:148 +0x7a7

goroutine 73 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc001066700)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_state.go:101 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:149 +0x815

goroutine 74 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc001066700)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:836 +0x4ff
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:155 +0x8b1

goroutine 75 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc001066700)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:773 +0x17a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:156 +0x911

goroutine 134 [select]:
github.com/tendermint/tendermint/proxy.(*multiAppConn).killTMOnClientError(0xc00121c1a0)
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/proxy/multi_app_conn.go:138 +0x16d
created by github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/proxy/multi_app_conn.go:118 +0x592

goroutine 136 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0012703c0)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x99a
created by github.com/syndtr/goleveldb/leveldb.newSession
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x469

goroutine 137 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc001180000)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:91 +0xf8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:148 +0x7a7

goroutine 138 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc001180000)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_state.go:101 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:149 +0x815

goroutine 139 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc001180000)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:836 +0x4ff
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:155 +0x8b1

goroutine 140 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc001180000)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:773 +0x17a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:156 +0x911

goroutine 141 [chan receive]:
github.com/tendermint/tendermint/state/txindex.(*IndexerService).OnStart.func1()
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/state/txindex/indexer_service.go:62 +0xbf
created by github.com/tendermint/tendermint/state/txindex.(*IndexerService).OnStart
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/state/txindex/indexer_service.go:60 +0x356

goroutine 238 [select]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc0017e71d0)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x99a
created by github.com/syndtr/goleveldb/leveldb.newSession
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x469

goroutine 239 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0017e5340)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:91 +0xf8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:148 +0x7a7

goroutine 240 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0017e5340)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_state.go:101 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:149 +0x815

goroutine 241 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0017e5340)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:836 +0x4ff
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:155 +0x8b1

goroutine 242 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0017e5340)
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:773 +0x17a
created by github.com/syndtr/goleveldb/leveldb.openDB
	/something/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:156 +0x911

goroutine 248 [syscall]:
os/signal.signal_recv()
	/usr/lib/go/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x1d
created by os/signal.Notify.func1.1
	/usr/lib/go/src/os/signal/signal.go:151 +0x2e

goroutine 249 [chan receive]:
github.com/tendermint/tendermint/libs/autofile.OpenAutoFile.func1()
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/libs/autofile/autofile.go:81 +0x3f
created by github.com/tendermint/tendermint/libs/autofile.OpenAutoFile
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/libs/autofile/autofile.go:80 +0x436

goroutine 250 [select]:
github.com/tendermint/tendermint/libs/autofile.(*AutoFile).closeFileRoutine(0xc0014ac410)
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/libs/autofile/autofile.go:104 +0xaa
created by github.com/tendermint/tendermint/libs/autofile.OpenAutoFile
	/something/go/pkg/mod/github.com/celestiaorg/celestia-core@v1.14.0-tm-v0.34.23/libs/autofile/autofile.go:86 +0x491

goroutine 42956 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc001c3e0c0)
	/something/go/pkg/mod/google.golang.org/grpc@v1.50.1/balancer_conn_wrappers.go:112 +0xf9
created by google.golang.org/grpc.newCCBalancerWrapper
	/something/go/pkg/mod/google.golang.org/grpc@v1.50.1/balancer_conn_wrappers.go:73 +0x22a
```

**Comment by SweeXordious** [comment]
fixed by: https://github.com/celestiaorg/celestia-app/pull/1368
